# Generated by Django 4.2.2 on 2023-06-29 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='globalsettings',
            options={'verbose_name': 'Global Settings', 'verbose_name_plural': 'Global Settings'},
        ),
    ]
