# Generated by Django 4.2.3 on 2023-07-31 12:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("profile", "0004_alter_basket_options_alter_order_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="avatar",
            field=models.ImageField(
                blank=True,
                default="media/default_avatar.jpg",
                null=True,
                upload_to="avatars/",
                verbose_name="Аватар",
            ),
        ),
    ]
