# Generated by Django 4.2.3 on 2023-08-01 11:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("profile", "0008_remove_basket_count_remove_basket_total_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="basketproduct",
            name="count",
            field=models.PositiveIntegerField(
                default=1, verbose_name="Количество в корзине"
            ),
            preserve_default=False,
        ),
    ]
