# Generated by Django 4.2.3 on 2023-08-01 13:41

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("profile", "0009_basketproduct_count"),
    ]

    operations = [
        migrations.RenameField(
            model_name="basketproduct",
            old_name="count",
            new_name="count_product",
        ),
    ]
