# Generated by Django 4.2.3 on 2023-08-02 09:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("profile", "0010_rename_count_basketproduct_count_product"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="delivery_type",
            field=models.CharField(
                choices=[
                    ("DEFAULT", "Обычная доставка"),
                    ("EXPRESS", "Экспресс доставка"),
                ],
                default="DEFAULT",
                max_length=8,
                verbose_name="Доставка",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="payment_type",
            field=models.CharField(
                blank=True,
                choices=[("CARD", "Моя карта"), ("OTHER", "Чужая карта")],
                max_length=8,
                null=True,
                verbose_name="Тип оплаты",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("NEW", "Новый"),
                    ("ACCEPT", "Принят"),
                    ("PAID", "Оплачен"),
                    ("WORK", "В работе"),
                    ("DONE", "Доставлен"),
                ],
                default="NEW",
                max_length=8,
                verbose_name="Статус заказа",
            ),
        ),
    ]
