# Generated by Django 4.2.3 on 2023-08-02 11:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("profile", "0013_orderproduct_count_product"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="address",
            field=models.CharField(
                blank=True, max_length=300, null=True, verbose_name="Адрес"
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="city",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Город"
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="payment_type",
            field=models.CharField(
                choices=[("CARD", "Моя карта"), ("OTHER", "Чужая карта")],
                default="CARD",
                max_length=8,
                verbose_name="Тип оплаты",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="total_cost",
            field=models.FloatField(default=0, verbose_name="Итоговая сумма"),
        ),
    ]
