# Generated by Django 4.2.3 on 2023-08-02 13:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("profile", "0014_alter_order_address_alter_order_city_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="payment_type",
            field=models.CharField(
                choices=[("ONLINE", "Моя карта"), ("SOMEONE", "Чужая карта")],
                default="ONLINE",
                max_length=8,
                verbose_name="Тип оплаты",
            ),
        ),
    ]
