# Generated by Django 4.2.3 on 2023-07-05 19:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="tag",
            old_name="category_id",
            new_name="category",
        ),
        migrations.AlterField(
            model_name="specificationproduct",
            name="specification",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="spec_spec",
                to="catalog.specification",
            ),
        ),
    ]
