# Generated by Django 4.2.3 on 2023-07-06 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_rename_category_id_tag_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_limited',
            field=models.BooleanField(default=False),
        ),
    ]
