# Generated by Django 4.2.3 on 2023-07-26 08:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_alter_banner_options_alter_catalog_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='src',
        ),
        migrations.AlterField(
            model_name='banner',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.product', verbose_name='Товар'),
        ),
        migrations.AlterField(
            model_name='review',
            name='author',
            field=models.CharField(max_length=2000, verbose_name='Автор'),
        ),
        migrations.AlterField(
            model_name='review',
            name='email',
            field=models.EmailField(max_length=200, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='review',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.product', verbose_name='Товар'),
        ),
        migrations.AlterField(
            model_name='review',
            name='rate',
            field=models.PositiveSmallIntegerField(verbose_name='Оценка'),
        ),
        migrations.AlterField(
            model_name='review',
            name='text',
            field=models.CharField(max_length=2000, verbose_name='Текст отзыва'),
        ),
        migrations.AlterField(
            model_name='sales',
            name='date_from',
            field=models.DateTimeField(verbose_name='Дата начала действия акционной цены'),
        ),
        migrations.AlterField(
            model_name='sales',
            name='date_to',
            field=models.DateTimeField(verbose_name='Дата окончания действия акционной цены'),
        ),
        migrations.AlterField(
            model_name='sales',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.product', verbose_name='Товар'),
        ),
        migrations.AlterField(
            model_name='sales',
            name='sale_price',
            field=models.FloatField(verbose_name='Цена товара по скидке'),
        ),
        migrations.AlterField(
            model_name='specification',
            name='name',
            field=models.CharField(max_length=2000, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='specificationproduct',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spec_product', to='catalog.product', verbose_name='Товар'),
        ),
        migrations.AlterField(
            model_name='specificationproduct',
            name='specification',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spec_spec', to='catalog.specification', verbose_name='Характеристика'),
        ),
        migrations.AlterField(
            model_name='specificationproduct',
            name='value',
            field=models.CharField(max_length=100, verbose_name='Значение'),
        ),
    ]
