# Generated by Django 4.2.3 on 2023-07-26 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_remove_image_src_alter_banner_product_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='src',
            field=models.ImageField(default=1, upload_to=''),
            preserve_default=False,
        ),
    ]
