# Generated by Django 4.2.3 on 2023-07-31 10:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0007_alter_product_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sales",
            name="date_from",
            field=models.DateField(verbose_name="Дата начала действия акционной цены"),
        ),
        migrations.AlterField(
            model_name="sales",
            name="date_to",
            field=models.DateField(
                verbose_name="Дата окончания действия акционной цены"
            ),
        ),
    ]
