# Generated by Django 4.2.3 on 2023-08-01 13:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0008_alter_sales_date_from_alter_sales_date_to"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="count",
        ),
        migrations.AddField(
            model_name="product",
            name="count_product",
            field=models.PositiveIntegerField(
                default=1, verbose_name="Количество на складе"
            ),
            preserve_default=False,
        ),
    ]
